version: '3'
services:
  nginx:
    build: docker
    image: vgc-client_nginx
    container_name: vgc-client_nginx
#    restart: always # Always restart container
    volumes:
      - ./docker/nginx/vgc-client.conf:/etc/nginx/conf.d/vgc-client.conf
      - ./dist:/www
    environment:
      - VIRTUAL_HOST=vgc.local # Enviroment variable needed for nginx proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=vgc.local # Enviroment variables needed for Let's Encrypt companion
      - LETSENCRYPT_EMAIL=solid_snake@vgc.local
    expose:
      - 80 # Expose http port
      - 443 # along with https port
    networks:
      - nginx-proxy # Connect this container to network named nginx-proxy, that will be described below

networks:
  nginx-proxy:
    external:
      name: ngninx-proxy-network # Reference our network that was created by Docker Compose when we launched our two main containers earlier. Name generated automaticaly. Use `docker network ls` to list all networks and their names.
