version: '3'
services:
  nginx:
    build: docker
    image: ${APP_NAME}_nginx
    container_name: ${APP_NAME}_nginx
    restart: always # Always restart container
    volumes:
      - ./docker/${APP_NAME}.conf:/etc/nginx/conf.d/${APP_NAME}.conf
      - ./dist:/www
    environment:
      - VIRTUAL_HOST=${APP_HOST} # Enviroment variable needed for nginx proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${APP_HOST} # Enviroment variables needed for Let's Encrypt companion
      - LETSENCRYPT_EMAIL=${SUPER_ADMIN_EMAIL}
    expose:
      - 80 # Expose http port
      - 443 # along with https port
    networks:
      - nginx-proxy # Connect this container to network named nginx-proxy, that will be described below

networks:
  nginx-proxy:
    external:
      name: ngninx-proxy-network # Reference our network that was created by Docker Compose when we launched our two main containers earlier. Name generated automaticaly. Use `docker network ls` to list all networks and their names.
